-- +goose Up
CREATE TABLE users (
    user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username TEXT NOT NULL,
    password TEXT NOT NULL,
    disable BOOLEAN NOT NULL DEFAULT FALSE,
    avatar TEXT NOT NULL DEFAULT '',
    role TEXT NOT NULL DEFAULT 'user',
    preset TEXT NOT NULL DEFAULT '',
    learner_profile JSON NOT NULL DEFAULT '{}'::json,
    extra JSON NOT NULL DEFAULT '{}'::json,
    creat_time TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT users_username_unique UNIQUE (username),
    CONSTRAINT users_username_not_blank CHECK (btrim(username) <> ''),
    CONSTRAINT users_password_not_blank CHECK (btrim(password) <> '')
);

-- +goose Down
DROP TABLE users;
